image: registry.gitlab.com/kodality/gitlab-builders/jdk-docker:latest

cache:
  key: "$CI_PROJECT_NAME"
  paths:
    - .gradle
    - build

before_script:
  - docker login -u $KODALITY_NEXUS_USER -p $KODALITY_NEXUS_PASSWORD docker.kodality.com

stages:
- build
- release

build:
  stage: build
  script:
    - ./gradlew clean assemble
  except:
    - main
  only:
    - branches

release snapshot:
  stage: release
  script:
    - ./gradlew clean assemble
    - ./gradlew publish

    - cd termx-app
    - docker build -t docker.kodality.com/termx-server:latest --build-arg BUILD_TIME=$BUILD_TIME .
    - docker push docker.kodality.com/termx-server:latest
  only:
    - main

release tag:
  stage: release
  script:
    - export APP_VERSION="$CI_COMMIT_REF_NAME"

    - ./gradlew clean assemble
    - ./gradlew publish -Pversion="$APP_VERSION"

    - cd termx-app
    - docker build -t docker.kodality.com/termx-server:$APP_VERSION --build-arg APP_VERSION=$APP_VERSION .
    - docker push docker.kodality.com/termx-server:$APP_VERSION
  only:
    - /^\d*\.\d*\.\d*$/
  except:
    - branches

