image: registry.gitlab.com/kodality-public/gitlab-builders/jdk-docker:latest

cache:
  key: "$CI_PROJECT_NAME"
  paths:
    - .gradle
    - build

before_script:
  - docker login -u $KODALITY_NEXUS_USER -p $KODALITY_NEXUS_PASSWORD docker.kodality.com

stages:
- build
- release

build:
  stage: build
  script:
    - ./gradlew clean assemble

release:
  stage: release
  script:
    - ./gradlew clean assemble
    - cd termserver-service
    - docker build -t docker.kodality.com/terminology-server --build-arg BUILD_TIME=$BUILD_TIME .
    - docker push docker.kodality.com/terminology-server
  only:
    - main
