name: Build ARM + AMD

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    tags:
      - '*.*.*'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: termx-server

defaults:
  run:
    working-directory: ./termx-app

jobs:

  build:

    runs-on: ubuntu-latest
    name: Build

    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build with Gradle
        run: ./gradlew clean assemble

      - name: Test
        run: ./gradlew check

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Print github.ref and github.base_ref
        run: |
          echo "Branch ref: ${{ github.ref }}"
          echo "Base ref: ${{ github.base_ref }}"

      - name: Set latest tag
        if: github.ref == 'refs/heads/main'
        run: echo "LATEST_TAG=latest" >> $GITHUB_ENV


      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}         
            type=raw,value=${{ env.LATEST_TAG }}
          flavor: |
            latest=auto

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./termx-app
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
