name: Cleanup Unused Container Versions

on:
  schedule:
    - cron: '0 0 * * 0' # Runs weekly on Sunday 00:00
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: List package versions
        id: list_versions
        run: |
          response=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/orgs/${{ github.repository_owner }}/packages/container/termx-server/versions")
          echo "$response" | tee response.json
          echo "::set-output name=response::$response"

      - name: Remove unused and untagged versions
        run: |
          response=${{ steps.curl_request.outputs.response }}
          echo "$response"
          for version in $(echo "$response" | jq -r '.[] | @base64'); do
            _jq() {
              echo ${version} | base64 --decode | jq -r ${1}
            }
            version_id=$(_jq '.id')
            echo "$version_id"
            downloads=$(_jq '.metadata.container.downloads')
            tags=$(_jq '.metadata.container.tags | length')

            #if [ "$downloads" -eq 0 ] && [ "$tags" -eq 0 ]; then
            if [ "$tags" -eq 0 ]; then
              echo "Removing unused and untagged version: $version_id"
              curl -X DELETE -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                "https://api.github.com/orgs/${{ github.repository_owner }}/packages/container/termx-server/versions/$version_id"
            fi
          done
